### ISSUE TITLE
Upgrade to v1.0.0 fails because of prefixed image.tag

### ISSUE THREAD

**Issue by mrsmall** [kloeckner-i/db-operator#104]
Hi, if I force my helm release to override the image.tag with 1.0.0 (without "v" prefix) then kubernetes tries to deploy image ghcr.io/kloeckner-i/db-operator:v1.0.0 (with "v" prefix)

helm command: helm upgrade -i db-operator db-operator/db-operator --set-string "image.tag=1.0.0"

The 1.0.0 image in your registry under https://github.com/kloeckner-i/db-operator/pkgs/container/db-operator does not have the "v" prefix, so image pull fails.

**Comment by mrsmall** [comment]
https://github.com/kloeckner-i/db-operator/pull/105

**Comment by hyunysmile** [comment]
Hi, 
We pushed image again with proper tag. 
Now `ghcr.io/kloeckner-i/db-operator:v1.0.0` should be available. 
Tag without "v" was one time human error. 
I'll close the MR.
Thanks for the report.
