### ISSUE TITLE
Database URL in Credentials Secret

### ISSUE THREAD

**Issue by tmaroschik** [kloeckner-i/db-operator#116]
First of all, I love the operator. It solves a lot of problems we experienced, running databases on kubernetes.

There is only one fragment missing for us. Often times applications require database credentials in the form of a database url like `mysql://user:secret@localhost/mydb` or `jdbc:mysql://mysql.db.server:3306/my_database?useSSL=false&serverTimezone=UTC`.

It would be awesome if the credentials secret contained such an url, so we can directly mount the secret as env var. As the URL format is application dependant, a go template like `mysql://{{ .user }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}` could be provided via the Database custom resource.

What do think of this?

**Comment by dabde** [comment]
hi @tmaroschik ,

think it's a possible feature to add to the db-operator. Think also the template sounds logical. So will create an internal ticket to add this.

But one point for "mount the secret as env var", you should avoid mounting secrets as env vars for security reasons. Some tools/plugins are logging ENV vars on a stacktrace or else. This means secrets can easy get exposed. So loading a file is more complicated, but also a little bit more secure.

thanks
