### ISSUE TITLE
[feature] S3 backup

### ISSUE THREAD

**Issue by stevehipwell** [kloeckner-i/db-operator#117]
It'd be great if this operator could support S3 compliant backup locations; specifically S3 for AWS users and Minio for a self contained cluster or testing purposes.

**Comment by dabde** [comment]
Hi,

thanks for the comment. Yes S3 would be nice. Think also to implement this is not to hard. It should already possible with a dirty workaround to use S3.

In the config we support already custom docker images for the backup:
https://github.com/kloeckner-i/db-operator/blob/master/controllers/backup/cronjob.go#L125

but the injection of the secrets is "hardcoded" :roll_eyes: 

https://github.com/kloeckner-i/db-operator/blob/master/controllers/backup/cronjob.go#L150
https://github.com/kloeckner-i/db-operator/blob/master/controllers/backup/cronjob.go#L166
https://github.com/kloeckner-i/db-operator/blob/master/controllers/backup/cronjob.go#L217

so you could misuse the filemount to inject your aws credentials to later use this in a custom entry-point script for the script and the same with the bucket name for your s3 storage location.

But it would better to remove the gcs dependency in this case, but it would currently not be a high prio issue for us.

**Comment by hyunysmile** [comment]
Hi, @stevehipwell 
Due to lack of resources, we are now only focusing on maintaining and bug fixing. 
Any feature request can be requested here: https://github.com/db-operator/db-operator
