### ISSUE TITLE
[feature] Helm 3 compatible chart

### ISSUE THREAD

**Issue by stevehipwell** [kloeckner-i/db-operator#118]
The current Helm chart isn't compatible with Helm 3 due to the CRDs being managed as resources. A quick and easy fix for this would be to add a value to conditionally create the CRDs. A better solution would be to move the CRDs into a `crds` folder, you could still add them to the resources but they could also be managed correctly by Helm 3 (Helm 2 is long since deprecated). The best solution would be to only support Helm 3 by updating the chart API version and removing the CRDs from the resources.

In the meantime, I want to be able to use this operator as it looks great and is exactly what I've been putting off building myself, I'm going to create an idiomatic helm v3 chart in my own [Helm repo](https://github.com/stevehipwell/helm-charts). I'd be more than happy to submit this back as a PR once it's done if you want it?

**Comment by dabde** [comment]
Hi,

I was try hard to remember why we was going this road. Think with helm v2 and the related CRD hooks we had bad experience and mostly with the migration to helm v3, we never touch this part again.

But feel free to open a PR.

**Comment by dabde** [comment]
from here: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/
```
This is also the reason behind removing templating support from CRDs.
``` 

Currently we generate the crd and add with helm template the related labels to the manifest. Think if we would move this to the `crd` folder direct, the label stuff would break.

Also for k8s 1.21+, we had to make changes to the CRD. From the page:
```
There is no support at this time for upgrading or deleting CRDs using Helm.
``` 

Would mean, if you upgrade your cluster and had again changes in the CRD, you need reinstall everything? o.O 

Also think we hitting with this chart already "Method #2". This chart is not installing direct db instances, for this we have a dedicated chart to avoid crd and resource installation at the same time.

**Comment by stevehipwell** [comment]
> Currently we generate the crd and add with helm template the related labels to the manifest. Think if we would move this to the crd folder direct, the label stuff would break.

As the Helm docs say, you shouldn't be templating anything in a CRD. Because the CRD is global and Helm doesn't manage it any more than creating the first instance there is no reason to add labels. Users should be encouraged to manage their CRDs outside helm as otherwise they wont ever get updates.

> Also for k8s 1.21+, we had to make changes to the CRD. From the page:

Helm shouldn't be used for managing CRDs, it's correct to list the latest ones in the `crds` folder so either a test install can use them (with instructions to manually delete them when uninstalling the chart) or an actual install can manually add/update them first and then install the chart with `--skip-crds`.

> Would mean, if you upgrade your cluster and had again changes in the CRD, you need reinstall everything? o.O

Helm doesn't manage your CRDs so it means you'd have to manually patch the CRDs. If you're changing the structure where the existing one doesn't work you'd need to do one of the following; add a new version and support both, add a new version with a conversion webhook, or delete and re-add the correct version.

> Also think we hitting with this chart already "Method #2". This chart is not installing direct db instances, for this we have a dedicated chart to avoid crd and resource installation at the same time.

You're not hitting option 2, that requires a folder called `crds`. Option 1 would be very easy to achieve as all you need to do is warp the CRD resource file with `{{- if .Values.skipCrds -}}...{{- end -}}`.

**Comment by dabde** [comment]
I get your points. Can also understand why they so careful with not managing the CRDs. But it's not a given limitation by CRDs itself. It's the caution to avoid any accident.

With Method #2 I mean separated Chart: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts

The db-operator helm chart is not direct using the crd in the installation. A change on the CRDs was ever done so, to not break the release or affect existing resources. The last change was come from  K8s API changes, not from CRD changes. I understand if we change the CRD API, we should create a new version and provide related migration paths.

We can move the crd in it's folder. Remove also the labels.

**Comment by dabde** [comment]
@stevehipwell have prepared #121, any comments for this?

**Comment by dabde** [comment]
changes already merged. added in the release not a small explanation how to migrate.
