### ISSUE TITLE
Does operator not support AWS RDS

### ISSUE THREAD

**Issue by andrewgkew** [kloeckner-i/db-operator#119]
Reading through the docs it seems that only GCP database or a generic DB (i.e. server already setup) is currently support. Is that correct?

**Comment by dabde** [comment]
Yes, we don't have implement any AWS support, related we don't use AWS.

So only way to work with AWS instances, is create one by hand or any other automation and provide the db-operator the instance as a generic one.

**Comment by dabde** [comment]
For adding AWS support, think the starting point is to extend this case block: https://github.com/kloeckner-i/db-operator/blob/master/controllers/dbinstance_controller.go#L182

then mostly clone this one: https://github.com/kloeckner-i/db-operator/blob/e84d79235d0cdfcdd4e4a2c36199cfc3e06e8c3c/pkg/utils/dbinstance/gsql.go

And replace the API communicate to aws one.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html#API_CreateDBInstance_Examples

or the related go lang lib:
https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.CreateDBInstance

For the unit test and integration test in the pipeline, we could first mark this as experimental and add them later. For gcloud we using a mock service to validate the api implementation. Don't know if aws has already something in place or someone need also create this in the future.

From my side, currently only using gcloud as cloud provider and have no need and also ne spare time to add this. But already other people ask for this as a feature. So maybe they happy if someone is adding this.

**Comment by ahaw023** [comment]
@dabde do you have an example of how to do the generic instance approach?

**Comment by ahaw023** [comment]
I would suggest a different approach. 

AWS has the ACK controllers for RDS https://github.com/aws-controllers-k8s/rds-controller 

Which you can use to create the instances. 

You can then use DB operator to provision databases as needed

@dabde - thanks for this. Traditionally I used Terraform for managing databases but we lock our RDS behind VPCs so this is great!

**Comment by hyunysmile** [comment]
Hi, @andrewgkew
Due to lack of resources, we are now only focusing on maintaining and bug fixing.
Any feature request can be requested here: https://github.com/db-operator/db-operator
