### ISSUE TITLE
PostgreSQL "public" schema

### ISSUE THREAD

**Issue by fbrnc** [kloeckner-i/db-operator#127]
When a PostgreSQL database is created a "public" schema will be created automatically. And all other users on the same database instance have full access to this public schema. 

> When a new database is created, PostgreSQL by default creates a schema named public and grants access on this schema to a backend role named public. All new users and roles are by default granted this public role, and therefore can create objects in the public schema.
https://aws.amazon.com/de/blogs/database/managing-postgresql-users-and-roles/

I think that's true for PostgreSQL in general and does not only apply to AWS RDS.

PostgreSQL recommends not using the public schema anymore and dropping it completely:

https://wiki.postgresql.org/wiki/Database_Schema_Recommendations_for_an_Application

I really like this db-operator and would like to see if there's an elegant solution to:
- remove the "public" schema after the database has been created (configurable in the "Database" CRD, e.g. `dropPublicSchema: true`)
- create a new schema (configurable in the "Database" CRD, e.g. `createSchema: <schemaName>`)
- (and maybe also revoke access to other databases' public schemas for user that are being generated)

**Comment by dabde** [comment]
Hi,

I will create an internal issue for this. But can't tell any time estimation at all. Lot's todo atm :sweat_smile: 

but thanks for the suggestion/hint on this topic.
