### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by tobikris** [kloeckner-i/db-operator#135]
This operator seems to fit my usecase of managing the databases in my k8s cluster. However as this cluster is running on ARM nodes, I cannot use it currently. Is it possible to publish docker images for ARM as well?
Thanks!

**Comment by allanger** [comment]
Hi! Starting from the version v1.6.2 we're pushing an ARM db-operator image. The [db-auth-gateway](https://github.com/kloeckner-i/db-auth-gateway) supports ARM too ([v0.1.8](https://github.com/orgs/kloeckner-i/packages/container/db-auth-gateway/24584250?tag=v0.1.8)).

There is one thing missing, [pgdump-gcs](https://github.com/kloeckner-i/pgdump-gcs) and [mydump-gcs](https://github.com/kloeckner-i/mydump-gcs) are not ported to ARM, so to have backup jobs running you will have to create your own image. Or you can contribute to our projects and add arm support there too.
