### ISSUE TITLE
Force deletion of databases

### ISSUE THREAD

**Issue by toabi** [kloeckner-i/db-operator#138]
We use a postgres exporter and because of the open connection to the database the db-operator can't delete the database because "it is used".

It would be cool if it could be deleted "[WITH (FORCE)](https://www.postgresql.org/docs/current/sql-dropdatabase.html)" here: https://github.com/kloeckner-i/db-operator/blob/master/pkg/utils/database/postgres.go#L210 (maybe as an option in the CRD)

**Comment by dabde** [comment]
Hi,

the db-operator brings already the option to enable a Prometheus postgres exporter on the instance level. (https://github.com/kloeckner-i/db-operator/blob/master/docs/enablingmonitoring.md)

If you want to list all the queries for each database, enable "pg_stat_statement" in your postgres instance. No need to deploy x-times the exporter for the same metrics.

thanks

**Comment by toabi** [comment]
Ah, okay. I have databases running which were created by just using the CRD and not the helm chart. It seems like setting the monitoring option there doesn't work as required resources are only created when using the instance helm chart.

**Comment by toabi** [comment]
Started to migrate to instances used by the helm-chart to enable monitoring.
