### ISSUE TITLE
An option to create a database from template

### ISSUE THREAD

**Issue by gmile** [kloeckner-i/db-operator#166]
Would it be possible to add an ability (a custom field in the CRD?) to create PostgreSQL database using what's known as a _template database_? For reference, template databases are a [feature in PostgreSQL](https://www.postgresql.org/docs/current/app-createdb.html) and can be used like this:

```
createdb pull-request-1234-db --template=staging-db
```

For context, our use case echoes what stated in the readme, e.g.:

> [...] support the on demand creation of test environments in CI/CD pipelines.

In our case, as part of CI/CD pipeline, when developers submit pull requests, we are creating what we call "review apps", e.g. a fully functional application built from a code in respective pull request. We would like to create such app & pre-create a database for it. The database for PR is a copy of our staging database.

**Comment by allanger** [comment]
I will raise up your request on one of our following internal meetings and come back with a result afterwards.

**Comment by hyunysmile** [comment]
Hi @gmile,
Thanks for your idea.
We are going to add this feature to create database from template.
At the beginning, we would like to take agile approach, so we will implement in a simple way with smallest change.
Basically the idea is that if the name of the template in the `Database` resource spec is defined, database will be created from the template. 
I think this should be enough for your use case.

**Comment by allanger** [comment]
@gmile Hi! Just to let you know, I'm planning to start working on this issue, once this PR is finished (#169).

**Comment by gmile** [comment]
@allanger noted, thank you for pushing this forward!

**Comment by allanger** [comment]
@gmile hey! Finally, it's merged. But now the project is migrated to the @db-operator organizations. The latest chart version should already have this feature

**Comment by gmile** [comment]
This is awesome, thank you so much! I will make sure to post our feedback here once we start using this ✨

**Comment by allanger** [comment]
@gmile Make sure to migrate to the new CRD API. The migration is not described anywhere yet, so if you have any troubles feel free to ask, I'll try to help
