### ISSUE TITLE
Provide a way to get secret from another secret

### ISSUE THREAD

**Issue by SimonHeimberg** [kloeckner-i/db-operator#17]
Mysql-Operators (like https://hub.helm.sh/charts/stable/mysql or https://github.com/oracle/mysql-operator/tree/master/mysql-operator) generate a secret containing the generated password. How can I get this secret into db-operator? The keys do not macht. Could you please give some hints or adapt the code?

Same question in so: https://stackoverflow.com/questions/61211378/use-kubernetes-secret-in-another-one

**Comment by dabde** [comment]
Hi,

currently, it's not supported for the related solutions.

The mysql helm chart is using different keys. Need to look what needs to be changed. To make this more dynamic, also related to other solutions.

The oracle mysql-operator is saving the password (https://github.com/oracle/mysql-operator/blob/master/pkg/resources/secrets/secret.go#L45) in the correct key, but the username is missing. 
Additional we create with our instance Chart already the secret (https://github.com/kloeckner-i/db-operator/blob/master/helm/db-instances/templates/dbinstance.yaml#L48). So this can result in Helm conflicts (resource already exist). 

We will take a look. I report back, if we plan internal to add this feature wish.

**Comment by dabde** [comment]
We plan to implement this as a feature and created an internal ticket for this.

**Comment by hyunysmile** [comment]
@SimonHeimberg Hi, you can re use mysql secret created by https://hub.helm.sh/charts/stable/mysql with `v0.3.0`
Just fill name and namespace of the existing secret in `adminSecretRef` field
```
apiVersion: kci.rocks/v1alpha1
kind: DbInstance
metadata:
  name: example-gsql
spec:
  adminSecretRef:
    Name: <name of secret existing>
    Namespace: <namespace of secret existing>
```

**Comment by SimonHeimberg** [comment]
Wonderful. I am amazed how quick issues are handled. Thank you very much indeed!
