### ISSUE TITLE
db-operator re-creates the whole database secret on PG_PASSWORD update instead of updating required fields

### ISSUE THREAD

**Issue by vladimir22** [kloeckner-i/db-operator#170]
Hi Team, I have updated `db-operator` to the latest version and caught the next:
The latest version of `db-operator` re-creates the whole Database Secret on "PG_PASSWORD Update Event".
By this action, `db-operator` erases 3d party metadata that might be inside the existing secret, like customer-specific annotations or secret's key like [ conjur-map key](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/secrets/config/config.go#L19)  used in the [conjur k8s-secrets-provider](https://docs.conjur.org/Latest/en/Content/Integrations/k8s-ocp/cjr-k8s-secrets-provider-ac.htm#Howitworks) solution.
It would be nice to update only the required "Database Secret Keys" instead of re-creating the whole secret resource.
Thanks.

**Comment by dabde** [comment]
Hi, 

will create an internal ticket and try to take a look.

thanks for the report.
