### ISSUE TITLE
Want to combine projects?

### ISSUE THREAD

**Issue by obeleh** [kloeckner-i/db-operator#180]
Hey. I’ve also been developing a db operator. For me it’s mostly started as a hobby project. But I’m now working towards making it usable in our company. We have similar goals, similar design. A list of things I’ve implemented:

- kuttl tests
- Unit test coverage of 45%
- Mysql support
- Postgres support
- Initial support for cockroach 
- Backups to s3
- Restore from s3
- Db copy jobs and cronjobs
- Privileges for Postgres and MySQL are WIP
- adding support for ecs and azure blobs would be easy with the architecture I have

https://github.com/obeleh/db-operator Docs are behind. But would you be interested in a call?

**Comment by hyunysmile** [comment]
Hi @obeleh,
Thank you for your interest and suggestion.
But due to resource reason, we are now focusing on maintaining and bug fixing. 
any suggestion can be addressed here: https://github.com/db-operator/db-operator
