### ISSUE TITLE
Postgres 15 support

### ISSUE THREAD

**Issue by bit-herder** [kloeckner-i/db-operator#186]
Hi, 

Thank you for all of your work. We use your operator and its very nice. I looked at the docs and I cannot find anywhere were postgres version compatibility is listed. I did try the operator in a new test cluster today in which i had the postgres DB set to `15`. I noticed that the databases were created as normal and the dbinstance is healthy. Also login to the databases with the user/password created by the operator is fine. However, when I try to set up one of the databases (in this case its grafana) I get errors when i try to create a table saying 

```
 PERMISSION DENIED FOR SCHEMA PUBLIC
 ```
 
I did a bit of research and it looks as if the default privs for the public schema are much tighter in postgres 15. See this article:

https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/

I tried the `grant` statement in that article and it fixed my issue. I wonder if this grant needs to be added to the operator if the version is 15? 

I do have to mention I am still using helm release `1.3.4` which i believe corresponds to `1.6.5` app version so I am not up to current, this may have been fixed since then but I am unable to find much in the way of docs about that. 

Thanks in advance for your assistance!

**Comment by allanger** [comment]
The development is moved here: https://github.com/db-operator/db-operator. Please create an issue there, I'll try to have a look soon
