### ISSUE TITLE
Q/A: Usage with CNPQ's Secret?

### ISSUE THREAD

**Issue by IngwiePhoenix** [kloeckner-i/db-operator#194]
Hello there!

I have been looking at methods to set up one postgres cluster and attach backups and alike to it, to then access it with different user/db/password assignments across different deployments and namespaces - in a way, to "centralize" my database and simplify my configuration. That way, I eventually came across this operator here.

How exactly do I make a `DbInstance` use the secrets provided by CNPG? Here's their keys:
```
# kubectl get -n postgres secrets/default-cluster-superuser -o json | jq '.data | keys[]'
"dbname"
"host"
"jdbc-uri"
"password"
"pgpass"
"port"
"uri"
"user"
"username"
```

Thank you and kind regards,
Ingwie

**Comment by allanger** [comment]
Hi, please consider re-creating this issue in https://github.com/db-operator/db-operator , this project is not maintained anymore
