### ISSUE TITLE
suggestion: optional more verbose name for mysql database

### ISSUE THREAD

**Issue by SimonHeimberg** [kloeckner-i/db-operator#22]
Currently I can not see which **mysql** database is from which project. 

When I undestand [stringShortener() in the code correctly](https://github.com/kloeckner-i/db-operator/blob/3aebca8fe086375dbf7947829f625472af0c98e6/pkg/controller/database/helper.go#L29), the name of the database is 16 characters of md5 hash.

I suggest to allow more verbose names. To remain BC compatible, shortening should be configurable in spec of `Database`. (Maybe not boolean, for potential feature variants.)

My suggestion for when configured verbose name:
`$dbName | trunc 44 | lower | replaceAll("[^a-z0-9]", "_") ~ '_' ~ $dbName | md5 | trunc 16)`
(dummy template code since I can not write GO)

<hr/>
sources for suggested name:

Permitted characters in unquoted identifiers (from [1]):
> ASCII: [0-9,a-z,A-Z$_] 
> (Extended: U+0080 .. U+FFFF )

lowercase (from [2]):
> To avoid problems caused by such differences, it is best to adopt a consistent convention, such as always creating and referring to databases and tables using lowercase names. 

max length `63` (from [3])

1: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
2: https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html
3: https://dev.mysql.com/doc/refman/5.7/en/identifier-length.html

**Comment by dabde** [comment]
The 16 Char limit comes from BC with MySQL 5.6.

Possible to move to the name schema like for google cloudSQL/Postgres.

We didn't had issues with hashed DB names, related we mostly never access the DB's in this way.
Add this to a internal meeting agenda.

**Comment by dabde** [comment]
We plan to implement this as a feature and created an internal ticket for this.

**Comment by SimonHeimberg** [comment]
I guess accessing the database may be interesting while the system is set up. (Then you are used to the old way.) But when all is running, this will rarely happen. So no priority.
