### ISSUE TITLE
Issues when using postgres DB which requires SSL

### ISSUE THREAD

**Issue by jrote1** [kloeckner-i/db-operator#38]
I am getting the following error
```
time="2020-09-21T22:28:53Z" level=info msg="Instance: name=shared-postgres Running"
time="2020-09-21T22:28:53Z" level=info msg="Instance: name=cockroachdb Creating"
time="2020-09-21T22:28:53Z" level=error msg="Instance: name=cockroachdb failed creating instance - creating generic db instance is not yet implimented"
time="2020-09-21T22:28:53Z" level=error msg="Instance: name=cockroachdb instance creation failed - creating generic db instance is not yet implimented"
```
Is it possible to enable verbose logging to get a better error?

**Comment by hyunysmile** [comment]
Hi, by setting `LOG_LEVEL` to `debug`, db connection error supposed to appear (https://github.com/kloeckner-i/db-operator/blob/master/pkg/utils/dbinstance/generic.go#L55)

**Comment by jrote1** [comment]
The error is what I thought it was
```
time="2020-09-22T08:16:00Z" level=debug msg="db conn test failed - failed to execute query: pq: node is running secure mode, SSL connection required"
time="2020-09-22T08:16:00Z" level=debug msg="instance doesn't exist, create instance"
time="2020-09-22T08:16:00Z" level=debug msg="creation failed"
```

**Comment by hyunysmile** [comment]
So I guess that's what you wanted to have? or you want SSL connection issue is resolved

**Comment by jrote1** [comment]
Yeah I need to be able to use this operator with a database that requires SSL Mode and if possibly a way to specify that SSL Mode is required in the generate ConfigMap for a database

**Comment by hyunysmile** [comment]
We will discuss internally and create ticket for it.

**Comment by jrote1** [comment]
Hi, do you have an idea if and when this will be worked on? Or should I consider fixing it myself?

**Comment by hyunysmile** [comment]
Hi, we aim for fixing it by next week. By then you can try quick fix by yourself. The problem comes from this line https://github.com/kloeckner-i/db-operator/blob/master/pkg/utils/database/postgres.go#L44.

**Comment by jrote1** [comment]
Hi, is there any update on this issue?

**Comment by hyunysmile** [comment]
Hi @jrote1,

v0.9.0 containing your requested feature is released.
Please find documentation here:
https://github.com/kloeckner-i/db-operator/blob/master/docs/creatinginstances.md#UsingSSLconnection
