### ISSUE TITLE
Cockroach DB support

### ISSUE THREAD

**Issue by jrote1** [kloeckner-i/db-operator#42]
It would be great if this could support cockroach DB, it is amazing database for scalability and resiliency. Currently when used it gives some errors but it should be a relatively easy addition as it uses the Postgres wire protocol and very similar syntax

**Comment by dabde** [comment]
Will discuss this internally if we have some resources to do this. But related we don't have at the moment any need for this, the chance is really low.

**Comment by jrote1** [comment]
Thank you very much for the update

**Comment by dabde** [comment]
Will close this issue. Like I was thinking, we currently don't need support for CockroachDB and related to this also no resources to make a implementation.

But feel free to open a pull request, if you want to add this.
