### ISSUE TITLE
Helm Releases missing for v0.5.0+

### ISSUE THREAD

**Issue by toabi** [kloeckner-i/db-operator#43]
The latest version in https://kloeckner-i.github.io/db-operator/helm/ is apparently v0.5.0

But this repository has a releases up to v0.9.0.

Would be cool if they are all easily available.

**Comment by dabde** [comment]
hi,

you can use with the helm release 0.5.0 also the latest db operator version. Maybe we should add information which version is working with which db-operator.

thanks.

**Comment by dabde** [comment]
Hi,

created a version matrix, which db operator is working fine with the related helm charts and k8s api version. hope it's solves your question.

https://github.com/kloeckner-i/db-operator/wiki/Version-Matrix

thanks.

**Comment by toabi** [comment]
That's awesome! Thank you.
