### ISSUE TITLE
Set Ownership of Database

### ISSUE THREAD

**Issue by toabi** [kloeckner-i/db-operator#44]
It would be nice to be able to set the ownership of the created database to the created user.

**Comment by dabde** [comment]
hi, 

you mean the database inside the database instance, or general the database instance? Can you explain more your idea?

thanks.

**Comment by toabi** [comment]
If a user wants to completely reset their database (single db inside an instance), an easy way is "DROP SCHEMA public CASCADE". (https://stackoverflow.com/a/13823560/743897) 

But as stated in https://www.postgresql.org/docs/13/sql-dropschema.html: `A schema can only be dropped by its owner or a superuser.`

Maybe a better full reset would even be [DROP DATABASE](https://www.postgresql.org/docs/13/sql-dropdatabase.html) and [CREATE DATABASE](https://www.postgresql.org/docs/13/sql-createdatabase.html). For that the user also has to be the owner.

**Comment by hyunysmile** [comment]
Hi toabi, 
You can DROP DATABASE by deleting db custom resource. And CREATE DATABASE by recreating the db resource. 
like `kubectl delete db certaindb` and `kubectl create -f certaindb.yml`
the user created by db-operator has all privileges on the created database such as you can create tables, drop tables, alter and so on. (see: https://github.com/kloeckner-i/db-operator/blob/b1c5b7ecae2fe52151e2a7aa0cdfcb144fb49da3/pkg/utils/database/postgres.go#L171)

is it answering user question? 
if not, please don't hesitate writing us back with your detail use case. that will be helpful to us.

**Comment by toabi** [comment]
Well, my use case was that I had a legacy application which in the past always deleted and created its own database. To delete the CRD resource I would have to give it access to the Kubernetes API.

But for now I wrote a little script which deletes everything in the database and resets the counters to 0.

**Comment by toabi** [comment]
I think this behaviour is fine, especially when #144 is done so the built-in monitoring feature can be used properly. With external monitoring setup the deletion fails because of active connections.

**Comment by jacksgt** [comment]
Hello!

I also have a use case where I would like to set the owner of the database.

Basically, the application is running the following as part of its schema migrations:
```
ALTER DATABASE "'<DB_NAME>" SET default_text_search_config = "english";
```
But only the database *owner* is allowed to do this: 

> You must be the owner of the configuration to use ALTER TEXT SEARCH CONFIGURATION.

* https://www.postgresql.org/docs/current/sql-altertsconfig.html
* https://www.postgresql.org/docs/15/textsearch-configuration.html
* https://www.postgresql.org/docs/15/runtime-config-client.html#GUC-DEFAULT-TEXT-SEARCH-CONFIG

Therefore the statement fails with:

```
ERROR 42501 (insufficient_privilege) must be owner of database <DB_NAME>
```

Do you have any recommendations for working around this issue?
