### ISSUE TITLE
Configurable MySQL name length limits

### ISSUE THREAD

**Issue by rombert** [kloeckner-i/db-operator#52]
I am just trying out this operator and so far it looks great!

I have hit a little problem with creating a database using the generic backend, probably because of an old MySQL version (5.6.43)

> time="2021-05-10T22:15:26Z" level=error msg="DB: namespace=lmn-system, name=example-db failed Creating - Error 1470: String 'lmn_system_example_db' is too long for user name (should be no longer than 16)"

I understand that this is quite an old version, and rather than asking everyone to live with much shorter names, perhaps one of these two solutions can be applied:

- be made configurable so I can set them in the helm chart
- auto-detected at runtime based on the MySQL version

Thanks for considering.

**Comment by rombert** [comment]
Thanks for your reply. Yes, I know MySQL 5.6 is quite old, but migration is not a possibility in the short term. I'm actually using the DB operator as part of a migration away from older systems but can't upgrade everything at once.

Would it be OK to adjust the user name limit from https://github.com/kloeckner-i/db-operator/blob/f07cb42a9a6186eefdf9fbdb21cb014d20b3f0a9/pkg/controller/database/databaseHelper.go#L144 ? I don't like the old fully hashed names too much, but I am not sure if I won't get into name clashes with 16 char names.

**Comment by dabde** [comment]
We create an internal issue to add this as a config parameter in the helm chart.

**Comment by rombert** [comment]
FWIW I was able to switch to MariaDB 10.0 away from MySQL 5.6. The versions are practically equivalent ( see https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/#drop-in-compatibility-of-specific-mariadb-versions ) and the name lengths are much better. According to https://mariadb.com/kb/en/create-user/#host-name-component

> Before MariaDB 10.6, the host name component could be up to 60 characters in length. Starting from MariaDB 10.6, it can be up to 255 characters.

So for me personally this is no longer an issue and feel free to close and not pursue.

**Comment by dabde** [comment]
okay, thx for the information.
