### ISSUE TITLE
Failure in creating databases leads to connection exhaustion

### ISSUE THREAD

**Issue by rombert** [kloeckner-i/db-operator#53]
I ran into a situation where failing to create a database leaks connections, eventually consuming all the connections available to the MySQL server.

I am using the same setup as in #52 - MySQL 5.6, generic DB instance. The MySQL database itself is create - I checked using the `mysql` shell but something else fails:

```
time="2021-05-10T23:35:38Z" level=info msg="Instance: name=example-generic Running"
time="2021-05-10T23:35:44Z" level=info msg="DB: namespace=lmn-system, name=ex start Creating"
time="2021-05-10T23:35:44Z" level=error msg="DB: namespace=lmn-system, name=ex failed creating database"
time="2021-05-10T23:35:44Z" level=error msg="DB: namespace=lmn-system, name=ex failed creating database - Error 1044: Access denied for user 'USER'@'HOSTSPEC' to database 'lmn_system_ex'"
time="2021-05-10T23:35:44Z" level=error msg="DB: namespace=lmn-system, name=ex failed Creating - Error 1044: Access denied for user 'USER'@'HOSTSPEC' to database 'lmn_system_ex'"
```

(I've replaced the actual user and host specification with placeholders).

After some point this ends up failing completely

```
time="2021-05-10T23:37:38Z" level=info msg="Instance: name=example-generic Running"
time="2021-05-10T23:37:45Z" level=info msg="DB: namespace=lmn-system, name=ex start Creating"
time="2021-05-10T23:37:45Z" level=error msg="DB: namespace=lmn-system, name=ex failed creating database"
time="2021-05-10T23:37:45Z" level=error msg="DB: namespace=lmn-system, name=ex failed creating database - Error 1040: Too many connections"
time="2021-05-10T23:37:45Z" level=error msg="DB: namespace=lmn-system, name=ex failed Creating - Error 1040: Too many connections"
```

The reason for the failure is something I will look into (perhaps again MySQL being too old) but I think the connection leak should definitely be fixed.

**Comment by dabde** [comment]
created an internal ticket to investigate the issue. thx for reporting.

**Comment by dabde** [comment]
Could also reproduce with newer mysql versions and without errors. Query handler was locking connection.

Connection leak is fixed. thx for the report.
