### ISSUE TITLE
Not compatible with k8s v1.22

### ISSUE THREAD

**Issue by toabi** [kloeckner-i/db-operator#85]
CustomResourceDefinition in v1beta1 is no longer served in kubernetes v1.22 so this can't be installed in such clusters.

**Comment by shawnnapora** [comment]
see pull #88 and my fork: https://github.com/shawnnapora/db-operator/

**Comment by dabde** [comment]
support for k8s 1.22 is added via #89 

helm chart: 0.6.9 and db-operator 0.14.2

**Comment by dabde** [comment]
@shawnnapora  @toabi ... any feedback, or can I close this issue?

**Comment by toabi** [comment]
Well, as it's compatible now, we can close this :) Thanks!
