### ISSUE TITLE
Feature request: Helm value for pod labels

### ISSUE THREAD

**Issue by davidfluck-kong** [kloeckner-i/db-operator#86]
Good afternoon. I would like to submit a small feature request. We would like the ability to pass pod labels through to the deployment template as part of a Helm release. Currently, though, there doesn't seem to be a way to do that. For example, in a sample values.yaml:

```yaml
podLabels:
  foo: bar
  baz: quux
```

I plan on submitting a pull request shortly, but let me know if there's anything specific I need to do or if you need any more information.

Thank you.

**Comment by dabde** [comment]
hi @davidfluck-kong ,

can you more explain, why you need an additional variable, extending the already filled field by `.Values.annotations`.

And should labels not be going into labels?

for your MR, maybe also extend the readme and build a new helm chart?

readme: https://github.com/kloeckner-i/db-operator/blob/master/helm/README.md?plain=1#L46
how to build helm chart: https://github.com/kloeckner-i/db-operator/blob/master/helm/README.md#releasing-new-chart-version (yes, still manual work, hope we can change this in the future to a github helm release action)

**Comment by davidfluck-kong** [comment]
Sure. We're using Calico network policies that [require the use of labels to target specific pods](https://docs.projectcalico.org/security/calico-network-policy#control-traffic-tofrom-endpoints-independent-of-namespace); my understanding is that it doesn't work with annotations. It would also be nice to have more generally. The Helm chart convention seems to be that `values.yaml` has a dictionary called `podLabels` to pass through to individual pods, in case someone wants to label them for other purposes too.

> And should labels not be going into labels?

Ah yes, you're right. (I told myself this would be a straightforward pull request, but I still found a way to make a mistake heh.) I can update the README and build a new Helm chart too.

Thanks for the quick response!

**Comment by dabde** [comment]
Ahhh for network policies. 

Do you need also this for the proxies? Or you connect directly then the application to the related database instances? 

If proxies needed, we need also touch some go code ;)
https://github.com/kloeckner-i/db-operator/blob/4e5532042edb799d48a7a90d892d2369c7b3a6e8/pkg/config/types.go#L44
... and more

**Comment by davidfluck-kong** [comment]
We aren't using any of the proxy features, as far as I'm aware. We're connecting directly.

I've fixed my previous error, updated the README, and generated a new Helm chart. Let me know if there's anything else I can do.

**Comment by davidfluck-kong** [comment]
Oops, I made another mistake with packaging the new Helm chart. Sorry, fixing.

**Comment by dabde** [comment]
feature is merged for helm chart version 0.6.7. 

closing issue.
